"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { ChartNoAxesCombined, Coins, Receipt, TrendingUp } from "lucide-react";
import { apiGet } from "@/lib/api";

type Row = { procedimento_id: number; quantidade: number; faturamento: number; custos_materiais: number; lucro: number };
type Report = { inicio: string; fim: string; atendimentos_realizados: number; clientes_do_dia: number; agendamentos: number; faturamento: number; custos_materiais: number; lucro: number; por_procedimento: Row[] };
const money = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });
const isoToday = () => new Date().toISOString().slice(0, 10);

export default function RelatoriosPage() {
  const [inicio, setInicio] = useState(isoToday()); const [fim, setFim] = useState(isoToday()); const [report, setReport] = useState<Report | null>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { if (!error) return; const timer = window.setTimeout(() => setError(null), 5000); return () => window.clearTimeout(timer); }, [error]);
  const load = useCallback(async (event?: FormEvent) => { event?.preventDefault(); try { setError(null); setReport(await apiGet<Report>(`/relatorios/resumo?inicio=${inicio}&fim=${fim}`)); } catch (reason) { if (event) setError(reason instanceof Error ? reason.message : "Não foi possível carregar o relatório."); else console.error("Falha ao carregar o relatório", reason); } }, [fim, inicio]);
  // O primeiro carregamento precisa sincronizar os dados externos ao montar a página.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load(); }, [load]);
  const cards = report ? [{ label: "Faturamento", value: money.format(report.faturamento), icon: Receipt }, { label: "Custos de materiais", value: money.format(report.custos_materiais), icon: Coins }, { label: "Lucro estimado", value: money.format(report.lucro), icon: TrendingUp }, { label: "Atendimentos", value: report.atendimentos_realizados, icon: ChartNoAxesCombined }] : [];
  return <div className="space-y-6"><header className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-sm font-medium uppercase tracking-[0.25em] text-fuchsia-700">MAYA · Relatório financeiro</p><h1 className="mt-2 text-2xl font-semibold text-slate-900">Faturamento, custos e lucro</h1><p className="mt-2 text-sm text-slate-500">Os custos usam o custo médio de materiais configurado em cada procedimento.</p></header><form onSubmit={load} className="flex flex-col gap-3 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm md:flex-row md:items-end"><label className="flex-1 text-sm text-slate-600">Início<input className="field mt-1" type="date" value={inicio} onChange={(e) => setInicio(e.target.value)} /></label><label className="flex-1 text-sm text-slate-600">Fim<input className="field mt-1" type="date" value={fim} onChange={(e) => setFim(e.target.value)} /></label><button className="primary-button md:w-auto">Atualizar relatório</button></form>{error && <p className="rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}{report && <><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{cards.map(({ label, value, icon: Icon }) => <div key={label} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><p className="text-sm text-slate-500">{label}</p><Icon size={18} className="text-fuchsia-700" /></div><p className="mt-4 text-2xl font-semibold text-slate-900">{value}</p></div>)}</div><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="mb-4 text-lg font-semibold text-slate-900">Resultado por procedimento</h2><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-xs uppercase tracking-wider text-slate-400"><tr><th className="p-3">Procedimento</th><th className="p-3">Qtd.</th><th className="p-3">Faturamento</th><th className="p-3">Materiais</th><th className="p-3">Lucro</th></tr></thead><tbody>{report.por_procedimento.map((row) => <tr key={row.procedimento_id} className="border-t border-slate-100"><td className="p-3">#{row.procedimento_id}</td><td className="p-3">{row.quantidade}</td><td className="p-3">{money.format(row.faturamento)}</td><td className="p-3">{money.format(row.custos_materiais)}</td><td className="p-3 font-semibold text-emerald-700">{money.format(row.lucro)}</td></tr>)}</tbody></table>{!report.por_procedimento.length && <p className="p-6 text-center text-sm text-slate-400">Nenhum atendimento concluído no período.</p>}</div></section></>}</div>;
}
